language: python

python:
      - '3.8'

before_script:
      - wget https://chromedriver.storage.googleapis.com/83.0.4103.14/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip -d /home/travis/build/Ghazi92e/P8_OC_atie_ghazi/
      - export CHROME_BIN=chromium-browser
      - pip install -r requirements.txt

env: 
  - DJANGO_SETTINGS_MODULE="purbeurre_project.settings.travis"

services:
      - postgresql
script:
      - python manage.py test
