language: python
python:
      - '3.8'

before_script:
      - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
      - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python3.8/bin/	
      - export CHROME_BIN=chromium-browser
      - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre_project.settings.travis"

services:
      - postgresql
script:
      - python manage.py test
