os: linux
dist: xenial

services:
  - postgresql
  - xvfb

language: python
python:
     - '3.8'

addons:
   chrome: stable

before_script:
      - pip install -r requirements.txt

env: 
  - DJANGO_SETTINGS_MODULE="purbeurre_project.settings.travis"

script:
     - python manage.py test
