language: python
python:
      - '3.8'

dist: xenial
addons:
  chrome: stable
before_install:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
before_script:
      - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="purbeurre_project.settings.travis"

services:
      - postgresql
script:
      - python manage.py test
